### ISSUE TITLE
Describe ESP8266 connection diagram

### ISSUE THREAD

**Issue by Sergyenko** [f-w-robots/MZG#5]

**Comment by Neschur** [comment]
https://123d.circuits.io/circuits/1477471-esp8266 variant 1
https://www.digikey.com/schemeit/#2lc9 - variant 2

**Comment by Neschur** [comment]
https://github.com/f-w-robots/MZG/wiki/Connection-diagrams - wiki

**Comment by Neschur** [comment]
https://www.digikey.com/schemeit/#2lci - new diagram, testing now
